/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author seape
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() throws SQLException {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Màn hình chính");
        setLocationRelativeTo(null);
        
        
        ChuyenManHinh chuyenManHinh = new ChuyenManHinh(panelView);
        chuyenManHinh.setView(phanmemPanel, phanmemLabel);
        chuyenManHinh.setView(tacnhanPanel, tacnhanLabel);
        chuyenManHinh.setView(usecasePanel, usecaseLabel);
        chuyenManHinh.setView(ktcnPanel, ktcnLabel);
        chuyenManHinh.setView(noisuyPanel,noisuyLabel);
        chuyenManHinh.setView(luongPanel, luongLabel);
        
        
        List<DanhMucBean> listItem = new ArrayList<>();
        listItem.add(new DanhMucBean("Phanmem", phanmemPanel, phanmemLabel));
        listItem.add(new DanhMucBean("Tacnhan", tacnhanPanel, tacnhanLabel));
        listItem.add(new DanhMucBean("Usecase",usecasePanel, usecaseLabel));
        listItem.add(new DanhMucBean("KTCN", ktcnPanel, ktcnLabel));       
        listItem.add(new DanhMucBean("Noisuy", noisuyPanel,noisuyLabel));
        listItem.add(new DanhMucBean("Luong", luongPanel, luongLabel));


        
        
        chuyenManHinh.setEvent(listItem);
        
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelView = new javax.swing.JPanel();
        phanmemPanel = new javax.swing.JPanel();
        phanmemLabel = new javax.swing.JLabel();
        tacnhanPanel = new javax.swing.JPanel();
        tacnhanLabel = new javax.swing.JLabel();
        usecasePanel = new javax.swing.JPanel();
        usecaseLabel = new javax.swing.JLabel();
        ktcnPanel = new javax.swing.JPanel();
        ktcnLabel = new javax.swing.JLabel();
        noisuyPanel = new javax.swing.JPanel();
        noisuyLabel = new javax.swing.JLabel();
        luongPanel = new javax.swing.JPanel();
        luongLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelViewLayout = new javax.swing.GroupLayout(panelView);
        panelView.setLayout(panelViewLayout);
        panelViewLayout.setHorizontalGroup(
            panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1001, Short.MAX_VALUE)
        );
        panelViewLayout.setVerticalGroup(
            panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        phanmemPanel.setBackground(new java.awt.Color(153, 204, 255));

        phanmemLabel.setText("Phần mềm");

        javax.swing.GroupLayout phanmemPanelLayout = new javax.swing.GroupLayout(phanmemPanel);
        phanmemPanel.setLayout(phanmemPanelLayout);
        phanmemPanelLayout.setHorizontalGroup(
            phanmemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, phanmemPanelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(phanmemLabel)
                .addGap(22, 22, 22))
        );
        phanmemPanelLayout.setVerticalGroup(
            phanmemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, phanmemPanelLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(phanmemLabel)
                .addContainerGap())
        );

        tacnhanPanel.setBackground(new java.awt.Color(153, 204, 255));

        tacnhanLabel.setText("Tác nhân");

        javax.swing.GroupLayout tacnhanPanelLayout = new javax.swing.GroupLayout(tacnhanPanel);
        tacnhanPanel.setLayout(tacnhanPanelLayout);
        tacnhanPanelLayout.setHorizontalGroup(
            tacnhanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tacnhanPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(tacnhanLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tacnhanPanelLayout.setVerticalGroup(
            tacnhanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tacnhanPanelLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(tacnhanLabel)
                .addGap(14, 14, 14))
        );

        usecasePanel.setBackground(new java.awt.Color(153, 204, 255));

        usecaseLabel.setText("Usecase");

        javax.swing.GroupLayout usecasePanelLayout = new javax.swing.GroupLayout(usecasePanel);
        usecasePanel.setLayout(usecasePanelLayout);
        usecasePanelLayout.setHorizontalGroup(
            usecasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usecasePanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(usecaseLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        usecasePanelLayout.setVerticalGroup(
            usecasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usecasePanelLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(usecaseLabel)
                .addGap(15, 15, 15))
        );

        ktcnPanel.setBackground(new java.awt.Color(153, 204, 255));

        ktcnLabel.setText("KTCN");

        javax.swing.GroupLayout ktcnPanelLayout = new javax.swing.GroupLayout(ktcnPanel);
        ktcnPanel.setLayout(ktcnPanelLayout);
        ktcnPanelLayout.setHorizontalGroup(
            ktcnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ktcnPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(ktcnLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ktcnPanelLayout.setVerticalGroup(
            ktcnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ktcnPanelLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(ktcnLabel)
                .addGap(15, 15, 15))
        );

        noisuyPanel.setBackground(new java.awt.Color(153, 204, 255));

        noisuyLabel.setText("Nội suy");

        javax.swing.GroupLayout noisuyPanelLayout = new javax.swing.GroupLayout(noisuyPanel);
        noisuyPanel.setLayout(noisuyPanelLayout);
        noisuyPanelLayout.setHorizontalGroup(
            noisuyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noisuyPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(noisuyLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        noisuyPanelLayout.setVerticalGroup(
            noisuyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, noisuyPanelLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(noisuyLabel)
                .addGap(15, 15, 15))
        );

        luongPanel.setBackground(new java.awt.Color(153, 204, 255));

        luongLabel.setText("Lương");

        javax.swing.GroupLayout luongPanelLayout = new javax.swing.GroupLayout(luongPanel);
        luongPanel.setLayout(luongPanelLayout);
        luongPanelLayout.setHorizontalGroup(
            luongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, luongPanelLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(luongLabel)
                .addGap(28, 28, 28))
        );
        luongPanelLayout.setVerticalGroup(
            luongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, luongPanelLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(luongLabel)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phanmemPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tacnhanPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usecasePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(luongPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noisuyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ktcnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addComponent(panelView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(phanmemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(tacnhanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(usecasePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(ktcnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(noisuyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(luongPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Menu().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ktcnLabel;
    private javax.swing.JPanel ktcnPanel;
    private javax.swing.JLabel luongLabel;
    private javax.swing.JPanel luongPanel;
    private javax.swing.JLabel noisuyLabel;
    private javax.swing.JPanel noisuyPanel;
    private javax.swing.JPanel panelView;
    private javax.swing.JLabel phanmemLabel;
    private javax.swing.JPanel phanmemPanel;
    private javax.swing.JLabel tacnhanLabel;
    private javax.swing.JPanel tacnhanPanel;
    private javax.swing.JLabel usecaseLabel;
    private javax.swing.JPanel usecasePanel;
    // End of variables declaration//GEN-END:variables
}
