/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import static View.KTCN.heSoPhucTap;
import static View.Luong.mucLuongBinhQuan1N1H;
import static View.Noisuy.noisuythoigianlaodong;
import static View.Noisuy.noisuythoigianlaodong2;
import static View.Tacnhan.diemTatCa;
import static View.Usecase.diemTungLoaiSD;

/**
 *
 * @author seape
 */
public class Phanmem extends javax.swing.JPanel {

    /**
     * Creates new form Luong
     */
    public Phanmem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"I", "Tính điểm trường hợp sử dụng (Use-case)", null, null, null},
                {"1", "Điểm Actor (TAW)", null, null, null},
                {"2", "Điểm Use-case (TBF)", null, null, null},
                {"3", "Tính điểm UUCP", "UUCP = TAW +TBF", null, null},
                {"4", "Hệ số phức tạp về KT-CN (TCF)", "TCF = 0,6 + (0,01 x TFW)", null, null},
                {"5", "Hệ số phức tạp về môi trường (EF)", "EF = 1,4 + (-0,03 x EFW)", null, null},
                {"6", "Tính điểm AUCP", "AUCP = UUCP x TCF x EF", null, null},
                {"II", "Nội suy thời gian lao động (P)", "P : người/giờ/AUCP", null, null},
                {"III", "Giá trị nỗ lực thực tế (E)", "E = 10/6 x AUCP", null, null},
                {"IV", "Mức lương lao động bình quân (H)", "H: người/giờ ", null, null},
                {"V", "Giá trị phần mềm nội bộ (G)", "G = 1,4 x E x P x H", null, "đồng"},
                {null, null, null, null, null}
            },
            new String [] {
                "TT", "Hạng mục", "Diễn giải", "Giá trị", "Ghi chú"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table1.setRowHeight(36);
        jScrollPane1.setViewportView(table1);

        jLabel1.setText("BẢNG XÁC ĐỊNH GIÁ PHẦN MỀM");

        jButton2.setText("Tính toán");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1113, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
     
        table1.getModel().setValueAt(diemTatCa, 1, 3);
        table1.getModel().setValueAt(diemTungLoaiSD, 2, 3);
        
        table1.getModel().setValueAt((double)diemTatCa + diemTungLoaiSD, 3, 3);
        table1.getModel().setValueAt(heSoPhucTap, 4, 3);
        table1.getModel().setValueAt(noisuythoigianlaodong2, 5, 3);
        double col6 = ((double)diemTatCa + diemTungLoaiSD) * heSoPhucTap * noisuythoigianlaodong2;
        table1.getModel().setValueAt(col6, 6, 3);
        table1.getModel().setValueAt(noisuythoigianlaodong, 7, 3);
        table1.getModel().setValueAt((10/(double)6) * col6, 8, 3);
        table1.getModel().setValueAt((double)mucLuongBinhQuan1N1H, 9, 3);
        table1.getModel().setValueAt(noisuythoigianlaodong * 1.4 * ((10/(double)6) * col6) * (double)mucLuongBinhQuan1N1H, 10, 3);
        
        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table1;
    // End of variables declaration//GEN-END:variables
}
