/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

/**
 *
 * @author seape
 */
public class Tacnhan extends javax.swing.JPanel {

    public static int diemTatCa = -1;
    
    /**
     * Creates new form Tacnhan
     */
    public Tacnhan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(640, 450));

        jLabel1.setText("Bảng tính toán điểm các tác nhân (actors) tương tác");

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Đơn giản ", "Thuộc loại giao diện của chương trình", null, null, null},
                {"2", "Trung bình ", "Giao diện tương tác hoặc phục vụ một giao thức hoạt động", null, null, null},
                {"3", "Phức tạp ", "Giao diện đồ họa", null, null, null},
                {null, "Cộng (1+2+3)", "TAW", null, null, null}
            },
            new String [] {
                "TT", "Loại Actor", "Mô tả", "Số tác nhân", "Điểm của từng loại tác nhân", "Ghi chú"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table1.setRowHeight(50);
        jScrollPane1.setViewportView(table1);

        jButton1.setText("Tính toán");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addComponent(jLabel1)
                .addContainerGap(124, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int soTacNhan1 = (int) table1.getModel().getValueAt(0, 3);
        int soTacNhan2 = (int)  table1.getModel().getValueAt(1, 3);
        int soTacNhan3 = (int) table1.getModel().getValueAt(2, 3);
        int diemtungLoai1 = (int) table1.getModel().getValueAt(0, 4);
        int diemtungLoai2 = (int) table1.getModel().getValueAt(1, 4);
        int diemtungLoai3 = (int) table1.getModel().getValueAt(2, 4);
        
        diemTatCa = soTacNhan1*diemtungLoai1 + soTacNhan2*diemtungLoai2 + soTacNhan3 * diemtungLoai3;
        
        table1.getModel().setValueAt(diemTatCa, 3, 4);

        
        System.out.println("diem tata ca: " + diemTatCa);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table1;
    // End of variables declaration//GEN-END:variables
}
